### ISSUE TITLE
UnicodeDecodeError when using 'ar' and 'uy' datasets

### ISSUE THREAD

**Issue by celsopneto** [malev/gender-detector#5]
I'm using the us and uk datasets normally, but when I try to use the other datasets I recieve this error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1078: invalid continuation byte`

Here is an example and the full error
: 
`import gender_detector as gd`
`detector = gd.gender_detector.GenderDetector('us')`
`detector2 = gd.gender_detector.GenderDetector('ar')`

detector.guess('Marcos')
Out[25]: 'male'

detector2.guess('Marcos')
Traceback (most recent call last):

  File "<ipython-input-26-5f6b7cd68ac7>", line 1, in <module>
    detector2.guess('Marcos')

  File "/home/cpneto/anaconda3/lib/python3.6/site-packages/gender_detector/gender_detector.py", line 25, in guess
    initial_position = self.index(name[0])

  File "/home/cpneto/anaconda3/lib/python3.6/site-packages/gender_detector/index.py", line 19, in __call__
    self._generate_index()

  File "/home/cpneto/anaconda3/lib/python3.6/site-packages/gender_detector/index.py", line 25, in _generate_index
    total = file.readline()  # Omit headers line

  File "/home/cpneto/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1078: invalid continuation byte

I believe this is a bug, but if there is any way to work around that I would be glad.

**Comment by celsopneto** [comment]
Apparently, arprocessed.csv and uyprocessed.csv are not UTF-8 encoded, I've tested changing arprocessed.csv to UTF-8 encoding on LibreOffice and it worked
